openapi: 3.0.1
info:
  title: Demo Swagger OpenAPI
  version: v0
  description: API cho việc quản lý người dùng.

servers:
  - url: http://localhost:8081
    description: Generated server url

paths:
  "/v1/register":
    post:
      summary: Tạo người dùng mới
      tags:
        - Account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '201':
          description: Tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: kientv84
        email:
          type: string
          example: kientv84@gmail.com

    AccountRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
        roles:
          type: array
          items:
            type: string




